name = "You"
port = 3000

[[app]]
name = "Bazarr"
url = "subs.example.com"
icon = "message-video"

[[app]]
name = "CloudCMD"
url = "files.example.com"
icon = "folder-multiple-outline"

[[app]]
name = "Cockpit"
url = "cp.example.com"
icon = "airplane"

[[app]]
name = "Feedbin"
url = "rss.example.com"
icon = "rss"

[[app]]
name = "Filestash"
url = "cloud.example.com"
icon = "package"

[[app]]
name = "Jackett"
url = "jackett.example.com"
icon = "tshirt-crew-outline"

[[app]]
name = "Lidarr"
url = "music.example.com"
icon = "music"

[[app]]
name = "Minio"
url = "minio.example.com"
icon = "server"

[[app]]
name = "Mylar"
url = "comics.example.com"
icon = "book-open-variant"

[[app]]
name = "Nextcloud"
url = "cloud.example.com"
icon = "weather-cloudy"

[[app]]
name = "Ombi"
url = "request.example.com"
icon = "file-find-outline"

[[app]]
name = "Pi-hole"
url = "pihole.example.com"
icon = "do-not-disturb"

[[app]]
name = "Plex"
url = "play.example.com"
icon = "plex"

[[app]]
name = "Portainer"
url = "port1.example.com"
icon = "docker"

[[app]]
name = "Radarr"
url = "movies.example.com"
icon = "filmstrip"

[[app]]
name = "Sonarr"
url = "tv.example.com"
icon = "television-box"

[[app]]
name = "Stackedit"
url = "md.example.com"
icon = "markdown"

[[app]]
name = "Transmission"
url = "dl.example.com"
icon = "progress-download"

[[app]]
name = "Ubooquity"
url = "opds.example.com"
icon = "library-shelves"

[[app]]
name = "Youtube-DL"
url = "yt.example.com"
icon = "youtube"

[[group]]
name = "Communicate"
[[group.links]]
name = "Discord"
url = "https://discord.com"
[[group.links]]
name = "Gmail"
url = "http://gmail.com"
[[group.links]]
name = "Slack"
url = "https://slack.com/signin"

[[group]]
name = "Cloud"
[[group.links]]
name = "Box"
url = "https://box.com"
[[group.links]]
name = "Dropbox"
url = "https://dropbox.com"
[[group.links]]
name = "Drive"
url = "https://drive.google.com"

[[group]]
name = "Design"
[[group.links]]
name = "Awwwards"
url = "https://awwwards.com"
[[group.links]]
name = "Dribbble"
url = "https://dribbble.com"
[[group.links]]
name = "Muz.li"
url = "https://medium.muz.li/"

[[group]]
name = "Dev"
[[group.links]]
name = "Codepen"
url = "https://codepen.io/"
[[group.links]]
name = "Devdocs"
url = "https://devdocs.io"
[[group.links]]
name = "Devhints"
url = "https://devhints.io"
                  
[[group]]
name = "Lifestyle"
[[group.links]]
name = "Design Milk"
url = "https://design-milk.com/category/interior-design/"
[[group.links]]
name = "Dwell"
url = "https://www.dwell.com/"
[[group.links]]
name = "Freshome"
url = "https://www.mymove.com/freshome/"
                  
[[group]]                  
name = "Media"
[[group.links]]
name = "Spotify"
url = "http://browse.spotify.com"
[[group.links]]
name = "Trakt"
url = "http://trakt.tv"
[[group.links]]
name = "YouTube"
url = "https://youtube.com/feed/subscriptions"
                  
[[group]]
name = "Reading"
[[group.links]]
name = "Instapaper"
url = "https://www.instapaper.com/u"
[[group.links]]
name = "Medium"
url = "http://medium.com"
[[group.links]]
name = "Reddit"
url = "http://reddit.com"

[[group]]                  
name = "Tech"
[[group.links]]
name = "TheNextWeb"
url = "https://thenextweb.com/"
[[group.links]]
name = "The Verge"
url = "https://theverge.com/"
[[group.links]]
name = "MIT Technology Review"
url = "https://www.technologyreview.com/"

[[provider]]
name = "Allmusic"
url = "https://www.allmusic.com/search/all/"
prefix = "/a"

[[provider]]
name = "Discogs"
url = "https://www.Discogs.com/search/all/"
prefix = "/di"

[[provider]]
name = "TheTVDB"
url = "https://www.thetvdb.com/search?query="
prefix = "/tv"

[[module]]
name = "Weather"
update_interval = 60
data = { city = "Helsinki" }

[[module]]
name = "Pi-hole"
update_interval = 60
data = { summaryEndpoint = "http://192.168.1.101/admin/api.php?summaryRaw" }
